### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tecktorious** [kibook/pmms#9] opened 2021-07-18 18:13 UTC
SCRIPT ERROR: @pmms/server.lua:556: attempt to index a nil value (local 'options')

**Comment by kibook** [comment] 2021-07-18 18:31
Could you describe the steps you did to cause the error?

**Comment by Tecktorious** [comment] 2021-07-18 19:12
I wrote next to musicphone pmm ..a panel opened I choose the near phonebox I paste the URL from YouTube and after I pressed start gave me this error

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by kibook** [comment] 2021-07-18 20:18
Does it happen with every URL or just a specific one? If it only happens with certain ones, could you provide an example?

**Comment by kibook** [comment] 2021-07-19 02:41
bebbee3 should make it so this will no longer produce an ugly fatal error, but it probably won't fix the root cause of the problem, which is that for some reason the `pmms:start` event is getting a `nil` value for the `options` table.

**Comment by Tecktorious** [comment] 2021-07-19 12:17
client.lua 1028 error again duibrowser ! i done all right ! still the error

**Comment by kibook** [comment] 2021-07-19 14:27
Please include the full text of the error message you receive, or a screenshot of the error in the console, it will help in trying to figure out what's going on. Could you also please provide an example URL you are trying to play that is giving you these errors? I play YouTube videos all the time with this without issues, so there's something else going on here.

**Closed** 2021-08-25 02:27 UTC
